<a href="https://colab.research.google.com/github/hamssik/python_programming/blob/main/11%E1%84%8C%E1%85%AE%E1%84%8E%E1%85%A1_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.arange(6)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a[0]

0

In [ ]:
a[1]

1

In [ ]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [ ]:
a2 = a[np.newaxis, :]

In [ ]:
a.shape

(6,)

In [ ]:
a2.shape

(1, 6)

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0, 1]

2

In [ ]:
a[0]

array([1, 2, 3, 4])

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.empty(2)

array([0., 0.])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
np.arange(4, 13, 3)

array([ 4,  7, 10])

In [ ]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
b = np.ones(2, dtype = np.int64)

In [ ]:
b

array([1, 1])

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
arr = np.sort(arr)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
y

array([[5, 6]])

In [ ]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
import numpy as np

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [ ]:
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

In [ ]:
a = np.arange(6)

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
print(a)

[0 1 2 3 4 5]


In [ ]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis, :]

In [ ]:
a2.shape

(1, 6)

In [ ]:
row_vector = a[np.newaxis, :]

In [ ]:
row_vector.shape

(1, 6)

In [ ]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
col_vector = a[:, np.newaxis]

In [ ]:
col_vector.shape

(6, 1)

In [ ]:
import numpy as np

In [ ]:
data = np.array([1, 2, 3])

In [ ]:
data

array([1, 2, 3])

In [ ]:
data[1]

2

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
data[-2:]

array([2, 3])

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a[a<5]

array([1, 2, 3, 4])

In [ ]:
print(a[a < 5])

[1 2 3 4]


In [ ]:
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


In [ ]:
a%2==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
b = 2

In [ ]:
if b >5 :
    print("정말 크네요")
else:
    print("좋아요")

좋아요


In [ ]:
b>7

False

In [ ]:
c = a[(a > 2) & (a < 11)]

In [ ]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
a[(a > 5) | (a == 5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.nonzero(a < 5)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [ ]:
b=np.nonzero(a < 5)

In [ ]:
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [ ]:
list(zip(b[0], b[1]))

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [ ]:
list_of_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [ ]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1 = a[3:8]

In [ ]:
arr1

array([4, 5, 6, 7, 8])

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

In [ ]:
a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.concatenate((a1, a2), axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
x = np.arange(1, 25)

In [ ]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
x.reshape(2, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.arange(1, 25).reshape(2, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x, 3)

[array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21, 22, 23, 24])]

In [ ]:
np.hsplit(x, (3, 4))

[array([1, 2, 3]),
 array([4]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24])]

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1, 1]

6

In [ ]:
a[2:]

array([[ 9, 10, 11, 12]])

In [ ]:
b1 = a[0, :]

In [ ]:
b1

array([1, 2, 3, 4])

In [ ]:
b1 = a.copy()

In [ ]:
b1[0] = 99

In [ ]:
b1

array([[99, 99, 99, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
data = np.array([1, 2])

In [ ]:
ones = np.ones(2, dtype=int)

In [ ]:
data + ones

array([2, 3])

In [ ]:
data - ones

array([0, 1])

In [ ]:
data * data

array([1, 4])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.sum()

10

In [ ]:
b = np.array([[1, 1], [2, 2]])

In [ ]:
b

array([[1, 1],
       [2, 2]])

In [ ]:
b.sum(axis=0)

array([3, 3])

In [ ]:
b.sum(axis=1)

array([2, 4])

In [ ]:
data = np.array([1.0, 2.0])

In [ ]:
data * 4

array([4., 8.])

In [ ]:
c = np.array([[1, 5], [2,4]])

In [ ]:
c

array([[1, 5],
       [2, 4]])

In [ ]:
c.max()

5

In [ ]:
c.min()

1

In [ ]:
a.min(axis=0)

2.0

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data[0,1]

2

In [ ]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
data[0:2, 0]

array([1, 3])

In [ ]:
data.max()

6

In [ ]:
data.min()

1

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))